# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
---
# profiles:
#   skip: Skip the service
#   build: Build the service

services:
  analyst-builder:
    image: postgres:16.1
    container_name: AnalystBuilder
    ports: ["5432:5432"]
    profiles: ["skip"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  data-expert:
    # username is `admin`, password is null
    image: trinodb/trino:443
    container_name: DataExpert
    ports: ["8080:8080"]
    profiles: ["skip"]

  data-lemur:
    image: postgres:14.11
    container_name: DataLemur
    ports: ["5433:5432"]
    profiles: ["skip"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  hacker-rank:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: HackerRank
    ports: ["1433:1433"]
    profiles: ["skip"]
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      # username is `SA`
      SA_PASSWORD: Test@123

  interview-query--postgres:
    image: postgres:14.3
    container_name: InterviewQuery_PostgreSQL
    ports: ["5434:5432"]
    profiles: ["skip"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  interview-query--mysql:
    image: mysql:8.0.35
    container_name: InterviewQuery_MySQL
    ports: ["3306:3306"]
    profiles: ["skip"]
    environment:
      # username is `root`
      MYSQL_ROOT_PASSWORD: mysql

  leetcode:
    image: mysql:8.0.36
    container_name: LeetCode
    ports: ["3307:3306"]
    profiles: ["skip"]
    environment:
      # username is `root`
      MYSQL_ROOT_PASSWORD: mysql

  namastesql:
    image: postgres:14.7
    container_name: NamasteSQL
    ports: ["5435:5432"]
    profiles: ["skip"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  sql-premier-league:
    image: postgres:16.8
    container_name: SQLPremierLeague
    ports: ["5436:5432"]
    profiles: ["skip"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  # Oracle is slow to start
  sql-short-reads:
    image: doctorkirk/oracle-19c:latest
    container_name: SQLShortReads
    ports: ["1521:1521"]
    profiles: ["skip"]
    environment:
      ORACLE_SID: DEFAULT
      # username is `SYSTEM`
      ORACLE_PWD: oracle

  strata-scratch:
    image: postgres:16.7
    container_name: StrataScratch
    ports: ["5437:5432"]
    profiles: ["skip"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
